# Generated by Django 3.0.7 on 2021-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurant_name',
        ),
    ]
