# Generated by Django 3.0.7 on 2021-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210524_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_picked',
            field=models.BooleanField(default=False),
        ),
    ]
