# Generated by Django 3.0.7 on 2021-06-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_restaurant_user'),
        ('order', '0007_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='res_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant'),
            preserve_default=False,
        ),
    ]
