# Generated by Django 3.0.7 on 2021-06-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_res_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='res_name',
        ),
    ]
