# Generated by Django 3.0.7 on 2021-05-15 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cus', 'Customer'), ('man', 'Manager'), ('adm', 'admin')], default='cus', max_length=3),
        ),
    ]
