# Generated by Django 3.0.7 on 2021-05-15 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210516_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cus', 'Customer'), ('man', 'Manager'), ('adm', 'admin')], default='cus', max_length=3),
        ),
    ]
