# Generated by Django 3.0.7 on 2021-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210519_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cus', 'Customer'), ('man', 'Manager'), ('adm', 'admin')], default='cus', max_length=3),
        ),
    ]
