# Generated by Django 3.0.7 on 2021-05-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210520_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cus', 'Customer'), ('man', 'Manager')], max_length=3),
        ),
    ]
