# Generated by Django 3.0.7 on 2021-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210521_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=42, max_length=15),
            preserve_default=False,
        ),
    ]
