# Generated by Django 3.0.7 on 2021-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Ajay kumar', max_length=100),
            preserve_default=False,
        ),
    ]
