# Generated by Django 3.2.4 on 2021-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
