# Generated by Django 3.2.4 on 2021-06-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210612_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='latitue',
            new_name='latitude',
        ),
    ]
